# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.cache/wt [current_project]
set_property parent.project_path D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC.xci
set_property is_locked true [get_files D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fifo_IIC -part xc7a15tftg256-1 -mode out_of_context

rename_ref -prefix_all fifo_IIC_

write_checkpoint -force -noxdef fifo_IIC.dcp

catch { report_utilization -file fifo_IIC_utilization_synth.rpt -pb fifo_IIC_utilization_synth.pb }

if { [catch {
  file copy -force D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.runs/fifo_IIC_synth_1/fifo_IIC.dcp D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.ip_user_files/ip/fifo_IIC]} {
  catch { 
    file copy -force D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_stub.v D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.ip_user_files/ip/fifo_IIC
  }
}

if {[file isdir D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.ip_user_files/ip/fifo_IIC]} {
  catch { 
    file copy -force D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_stub.vhdl D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.ip_user_files/ip/fifo_IIC
  }
}
