# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC.xci
# IP: The module: 'fifo_IIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC/fifo_IIC.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_IIC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_IIC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC.xci
# IP: The module: 'fifo_IIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC/fifo_IIC.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_IIC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Hui/RTL/prj_ft2232h_bak_17_copy/prj_ft2232h/prj_ft2232h.srcs/sources_1/ip/fifo_IIC/fifo_IIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_IIC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
